### ISSUE TITLE
Create a range input

### ISSUE THREAD

**Issue by shaharsol** [shaharsol/jQuery-Knob#1]
I'd like to use the wonderful JQuery Knob as a range input. I want to render a knob where users are able to mark two points on the knob: a start of a range and an end of a range, and have the knob able to provide the data when I need it, e.g. on form submission. 

To clarify with an example, let's say this range knob is going to be used in a weather app, where the user wants to be alerted on winds coming from a certain direction, for example S-SW wind, where the range is 180-225. So he needs to mark a range starting at 180 degrees and ending at 225 degrees.

codemill$30

**Comment by shaharsol** [comment]
@weisk has been assigned to this task.

**Comment by shaharsol** [comment]
@weisk has been unassigned from this task.

**Comment by weisk** [comment]
sorry I clicked the wrong button ...

**Comment by shaharsol** [comment]
@antonykidis has been assigned to this task.

**Comment by T1T4N** [comment]
@shaharsol Although I am a bit late and the task is gone from codemill, I have created a modified jQuery knob with the ability to select starting position. You can contact me for further details

**Comment by shaharsol** [comment]
@T1T4N thanks, however @antonykidis has already took the task and I want to let him a fair chance to complete it.

**Comment by shaharsol** [comment]
@antonykidis has been unassigned from this task.

**Comment by shaharsol** [comment]
@muhammadazani has been assigned to this task.

**Comment by shaharsol** [comment]
Hi @muhammadazani, thanks for working on this, please let me know if you have any questions.

**Comment by shaharsol** [comment]
@muhammadazani any progress?

**Comment by shaharsol** [comment]
@muhammadazani has been unassigned from this task.

**Comment by shaharsol** [comment]
@stoutZero has been assigned to this task.

**Comment by shaharsol** [comment]
@stoutZero has been unassigned from this task.

**Comment by shaharsol** [comment]
@T1T4N has been assigned to this task.
